### ISSUE TITLE
long press on mobile brings up context in the MIDDLE of the mouse click?

### ISSUE THREAD

**Issue by burtonator** [TimboKZ/react-context-menu-wrapper#2]
Seems like long press brings up the context menu centered over the pointer.  

It the context menu should be above or below... not center

**Comment by v1ndic4te** [comment]
This one is working as intended, but thinking about it again it might actually make more sense to put the menu above the cursor, but definitely not below.

I'm quite busy with other things at the moment so if you need an quick fix, consider changing these lines:
https://github.com/v1ndic4te/react-context-menu-wrapper/blob/master/src/util.js#L431-L436

I'll adjust the menu placement eventually.

**Comment by burtonator** [comment]
Fair enough and I can fix and send a PR.  

Is this standard UX for context menus on mobile?  I honestly don't know.

The issue I have is that once it's up it's easy to click something plus your finger is obscuring part of the menu.

**Comment by TimboKZ** [comment]
[Changed](https://github.com/TimboKZ/react-context-menu-wrapper/commit/7f7c212e1d78f9ea9a12b156d9712c65cee23859) the behaviour in v1.0.7 to make the menu appear above the tap.
